[package]
name = "bytepiece-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytepiece-rs = {workspace = true}
clap = {features = ["derive"], version = "4.5.21"}